### ISSUE TITLE
The Electron version installed needs to be at least 1.7.0

### ISSUE THREAD

**Issue by ivanhuay** [nccgroup/wssip#1]
when i run wssip is giving me this error

> The Electron version installed needs to be at least 1.7.0

but the [last release](https://electron.atom.io/releases/) is 1.6.8

**Comment by SteelPhase** [comment]
[Take a look at their GitHub page](https://github.com/electron/electron/releases/tag/v1.7.1).

**Comment by thekettu** [comment]
That was my mistake, for some weird reason npm somehow tagged this as release. Try `npm install -g electron@1.7` ? I've also updated the README and package.json for this.

**Comment by ivanhuay** [comment]
Try but I could not make it work wssip

i run 
```
wssip # Without showing error or application
```
later y run
```
wssip ; echo $?
#output
1
```
So there is some error that is not logging

**Comment by ivanhuay** [comment]
Try installing it from the source code

```
npm i --production

npm WARN prefer global node-gyp@3.5.0 should be installed with -g

> node-libcurl@1.1.0 install /home/xxxx/Dev/lib/wssip/node_modules/node-libcurl
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-electron-v1.7-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.1.0 and electron@1.7.0 (electron-v1.7 ABI) (falling back to source compile with node-gyp) 
Could not run curl-config, please make sure libcurl dev package is installed.
Output: /bin/sh: 1: curl-config: not found

gyp: Call to 'node "/home/xxxx/Dev/lib/wssip/node_modules/node-libcurl/tools/curl-config.js"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/xxxx/Dev/lib/wssip/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-78-generic
gyp ERR! command "/usr/local/bin/node" "/home/xxxx/Dev/lib/wssip/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/xxxx/Dev/lib/wssip/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/home/xxxx/Dev/lib/wssip/node_modules/node-libcurl/lib/binding" "--dist-url=https://atom.io/download/electron"
gyp ERR! cwd /home/xxxx/Dev/lib/wssip/node_modules/node-libcurl
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /home/xxxx/Dev/lib/wssip/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/xxxx/Dev/lib/wssip/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/xxxx/Dev/lib/wssip/node_modules/node-libcurl/lib/binding --dist-url=https://atom.io/download/electron' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/xxxx/Dev/lib/wssip/node_modules/node-libcurl/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-78-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/xxxx/Dev/lib/wssip/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/xxxx/Dev/lib/wssip/node_modules/node-libcurl
node-pre-gyp ERR! node -v v7.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /home/xxxx/Dev/lib/wssip/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/xxxx/Dev/lib/wssip/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/xxxx/Dev/lib/wssip/node_modules/node-libcurl/lib/binding --dist-url=https://atom.io/download/electron' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-libcurl@1.1.0 (node_modules/node-libcurl):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-libcurl@1.1.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by rustymagnet3000** [comment]
I hit the same..

<img width="430" alt="image" src="https://user-images.githubusercontent.com/5367141/27488126-d4149572-582d-11e7-8d52-364f0b0a4045.png">

**Comment by thekettu** [comment]
Apologies, this has been a rough few weeks and I'm getting back to this. Closing this issue as electron 1.7 needs to be installed *globally* as per the readme. This is due to electron-forge somehow mandating that Electron be installed in the devDependencies for some reason, otherwise this would be in the dependencies of package.json.

@rustymagnet3000 I should be pushing out a new commit shortly that might be able to fix it, but why not just use the `wssip` command line tool instead of linking to the Electron binary directly? `/usr/local/bin/wssip` should be a shortcut, not the working directory of wssip.
