### ISSUE TITLE
ELIFECYCLE

### ISSUE THREAD

**Issue by Csati94** [nccgroup/wssip#10]
When I wanted to open a window, the wssip caught the request and died immediately.
![screenshot from 2018-04-19 10-52-04](https://user-images.githubusercontent.com/15878064/38981699-4c879896-43c0-11e8-993e-fd0b9246014e.png)

**Comment by mttat** [comment]
Similar issue encountered on interacting with a live web connection. 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.8.0
3 info using node@v8.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle wssip@1.1.2~prestart: wssip@1.1.2
6 info lifecycle wssip@1.1.2~start: wssip@1.1.2
7 verbose lifecycle wssip@1.1.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle wssip@1.1.2~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/mttat/Documents/wssip/node_modules/.bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle wssip@1.1.2~start: CWD: /home/mttat/Documents/wssip
10 silly lifecycle wssip@1.1.2~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle wssip@1.1.2~start: Returned: code: 1  signal: null
12 info lifecycle wssip@1.1.2~start: Failed to exec start script
13 verbose stack Error: wssip@1.1.2 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid wssip@1.1.2
15 verbose cwd /home/mttat/Documents/wssip
16 verbose Linux 4.18.0-kali2-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.11.2
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error wssip@1.1.2 start: `electron .`
22 error Exit status 1
23 error Failed at the wssip@1.1.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
