### ISSUE TITLE
Electron fails to start

### ISSUE THREAD

**Issue by t3h2mas** [nccgroup/wssip#2]
I can't get wssip to run, I followed both the yarn instructions, as well as running from the source. When I try to execute the `npm start` command, I get this:

```
9 verbose lifecycle wssip@1.0.11~start: CWD: /Users/thomas/Code/sec/wssip
10 silly lifecycle wssip@1.0.11~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle wssip@1.0.11~start: Returned: code: 1  signal: null
12 info lifecycle wssip@1.0.11~start: Failed to exec start script
13 verbose stack Error: wssip@1.0.11 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/thomas/.nvm/versions/node/v8.2.1/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/thomas/.nvm/versions/node/v8.2.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid wssip@1.0.11
15 verbose cwd /Users/thomas/Code/sec/wssip
16 verbose Darwin 16.1.0
17 verbose argv "/Users/thomas/.nvm/versions/node/v8.2.1/bin/node" "/Users/thomas/.nvm/versions/node/v8.2.1/bin/npm" "start"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error wssip@1.0.11 start: `electron .`
22 error Exit status 1
23 error Failed at the wssip@1.0.11 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

versions
```
λ ~/code/sec/wssip/ master* electron -v
v1.7.5
λ ~/code/sec/wssip/ master* node -v
v8.2.1
λ ~/code/sec/wssip/ master* npm -v
5.3.0
```

Any advice?

**Comment by waqasrana** [comment]
i had same error. i noticed following errors during install


>node-pre-gyp ERR! Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-electron-v1.7-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.1.0 and electron@1.7.0 (electron-v1.7 ABI) (falling back to source compile with node-gyp)

**Comment by thekettu** [comment]
Try the dev branch and let me know if that works for you? I fixed several big errors and re-wrote a large portion of the source to fix a lot of the source of crashes.
