### ISSUE TITLE
WSSiP v1.0.9 Windows Binary was shut down sliently

### ISSUE THREAD

**Issue by kaito834** [nccgroup/wssip#3]
I launched WSSiP v1.0.9 on Windows 10, and tried to connect wss://echo.websocket.org at [websocket.org](https://www.websocket.org/echo.html). Then, WSSiP v1.0.9 was shut down silently. No error was not recorded at Windows Event log. Please let me know if you need more information to investigate  this issue.

My environments:
- Windows 10 (64 bit)
- Google Chrome 59.0.3071.115

My procedures:
1. Download [wssip-1.0.9-win32.zip](https://github.com/nccgroup/wssip/releases/download/v1.0.9/wssip-1.0.9-win32.zip)
2. Unzip the wssip-1.0.9-win32.zip, and launch WSSiP.exe
3. Run [Options] > [Start/Stop server] on WSSiP UI
4. Open https://www.websocket.org/echo.html on Google Chrome
5. Set localhost:8080 as proxy on Google Chrome
6. Press [Connect] button at websocket.org on Google Chrome
7. Then, WSSiP is shut down silently

**Comment by kaito834** [comment]
Using WSSiP 1.1.0, this issue seems to be solved. But, WSSiP 1.1.0 could not proxy WebSocket connection between echo.websocket.org and client. An error associated with SSL/TLS happened.

# My Environment
- Windows 10 (64 bit)
- Node.js v8.3.0
- Mozilla Firefox 54.0.1

# My Procedures
1. Install Node.js v8.3.0; the latest version of Node.js
2. git clone -b dev https://github.com/nccgroup/wssip
3. cd wssip
4. npm i electron@1.7
5. npm i node-forge
6. npm i debug
7. npm i --production
8. set DEBUG=wssip:*
9. npm start
10. Run [Options] > [Start/Stop server] on WSSiP UI
11. Open https://www.websocket.org/echo.html on Firefox
12. Set 127.0.0.1:8888 as proxy on Firefox
13. Press [Connect] button at websocket.org on Firefox. 
14. Confirm the error logs below at Windows command prompt and websocket.org.

## Error logs
websocket.org
```
ERROR: undefined
DISCONNECTED
```

Windows command prompt
```
Mon, 14 Aug 2017 13:00:10 GMT wssip:mitmengine [ { shortName: 'OU', value: 'Domain Control Validated' },
  { shortName: 'CN', value: '*.websocket.org' } ]
Mon, 14 Aug 2017 13:00:10 GMT wssip:mitmengine CONNECT: [HTTPS] echo.websocket.org:443 <-> localhost:55249
Mon, 14 Aug 2017 13:00:10 GMT wssip:mitmengine ERROR: [proxy#clientError] [clientError] [read ECONNRESET]
Mon, 14 Aug 2017 13:00:10 GMT wssip:mitmengine REQUEST: [NODE:0] [GET] http://detectportal.firefox.com/success.txt [HTTP/1.1]
Mon, 14 Aug 2017 13:00:10 GMT wssip:mitmengine ERROR: [mitmengine#_setupHttpServer] [SUBPROXY_CLIENTERROR:t:echo.websocket.org:443] [101057795:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:c:\e\workspace\electron-win-x64\vendor\node\deps\openssl\openssl\ssl\s3_pkt.c:1493:SSL alert number 48
```

**Comment by irsdl** [comment]
I had the same problem and compiled the v1.1 and now it is not closing it instantly. However, it still crashes in the middle of working with it which is very annoying especially as I lose my requests.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle wssip@1.1.0~prestart: wssip@1.1.0
6 silly lifecycle wssip@1.1.0~prestart: no script for prestart, continuing
7 info lifecycle wssip@1.1.0~start: wssip@1.1.0
8 verbose lifecycle wssip@1.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle wssip@1.1.0~start: PATH: [REDACTED]
10 verbose lifecycle wssip@1.1.0~start: CWD: c:\[REDACTED]\wssip
11 silly lifecycle wssip@1.1.0~start: Args: [ '/d /s /c', 'electron .' ]
12 silly lifecycle wssip@1.1.0~start: Returned: code: 1  signal: null
13 info lifecycle wssip@1.1.0~start: Failed to exec start script
14 verbose stack Error: wssip@1.1.0 start: `electron .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid wssip@1.1.0
16 verbose cwd c:\[REDACTED]\wssip
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.11.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error wssip@1.1.0 start: `electron .`
22 error Exit status 1
23 error Failed at the wssip@1.1.0 start script 'electron .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the wssip package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs wssip
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls wssip
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by arbazkiraak** [comment]
Facing the similar problem.
